spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: WelcomeApp
              uri: lb://WELCOME-SERVICE
              predicates:
                - Path=/msg/**
