server:
  port: 1010

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: WelcomeApp
              uri: lb://WELCOME-SERVICE
              predicates:
                - Path=/msg/**
